name: Build and Package Python Executables

on:
  workflow_dispatch:


jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.4

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
      shell: bash

    - name: Install PyInstaller
      run: |
        pip install pyinstaller
      shell: bash

    - name: Build Executable
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          pyinstaller --onefile --add-data "src/assets;." -n SLQimaoDownloaderWindows -i main.ico src/app.py
        elif [ "${{ matrix.os }}" == "macos-latest" ]; then
          pyinstaller --onefile --add-data "src/assets:." -n SLQimaoDownloaderMacOS src/app.py
        else
          pyinstaller --onefile --add-data "src/assets:." -n SLQimaoDownloaderUbuntu src/app.py
        fi
      shell: bash

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: executables
        path: dist/
